# Generated by Django 3.2.9 on 2021-12-04 11:17

import api_app.services.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('service_image', models.ImageField(blank=True, default=api_app.services.models.get_default_service_image, null=True, upload_to=api_app.services.models.get_service_image_filepath)),
                ('tags', models.TextField(blank=True, null=True)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=6)),
                ('revision', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api_app.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api_app.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'created', 'updated'],
            },
        ),
    ]
